### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by candasm** [Ardakilic/dizici#1]
I think MySQL is unnecessary. You can use SQLite as well.

**Comment by Ardakilic** [comment]
SQLite is already supported, since the connection layer is actually [illumminate/database](https://github.com/illuminate/database) and just like Laravel, it supports SQLite natively :smile: 

The connection lines will be just like https://github.com/laravel/laravel/blob/becd774e049fb451aca0c7dc4f6d86d7bc12256c/config/database.php#L49-L52

Just change the `database_path('database.sqlite')` to something like `__DIR__.'/database.sqlite'`.

You can also refer to https://github.com/illuminate/database/blob/5292833ddb13f86b22370ca2abaa97bffc7da64a/Connectors/SQLiteConnector.php if you're unsure what to insert.

**Comment by Ardakilic** [comment]
Oh and, by the way:

https://github.com/Ardakilic/dizici/releases

Check the 1.0.0 :)
